import { decryptSecret, encryptSecret } from "./connectors";
import { id, now } from "./db";
import type { ControlEnv } from "./types";

const encoder = new TextEncoder();
function base64url(value:Uint8Array){return btoa(String.fromCharCode(...value)).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"");}
function endpoint(value:string){const url=new URL(value);if(url.protocol!=="https:"||url.hostname==="localhost"||url.hostname.endsWith(".local")||/^\d+\.\d+\.\d+\.\d+$/.test(url.hostname))throw new Error("Webhook endpoint must be a public HTTPS URL");return url.toString();}
export async function signAgentWebhook(secret:string,timestamp:string,body:string){return base64url(new Uint8Array(await crypto.subtle.sign("HMAC",await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),encoder.encode(`${timestamp}.${body}`))));}

export async function createAgentWebhook(env:ControlEnv,input:{ownerSub:string;organizationId?:string|null;projectId?:string|null;label:string;endpoint:string;eventTypes:string[]}){
  if(!input.label?.trim()||!input.eventTypes?.length)throw new Error("Webhook label and event types are required");
  const secret=`gbwh_${base64url(crypto.getRandomValues(new Uint8Array(32)))}`;const webhookId=id("awh");const timestamp=now();
  await env.CONTROL_DB.prepare(`INSERT INTO agent_api_webhooks (id,owner_sub,organization_id,project_id,label,endpoint,secret_ciphertext,event_types_json,created_at,updated_at)
    VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(webhookId,input.ownerSub,input.organizationId||null,input.projectId||null,input.label.trim().slice(0,120),endpoint(input.endpoint),await encryptSecret(env,secret),JSON.stringify([...new Set(input.eventTypes)]),timestamp,timestamp).run();
  return{id:webhookId,secret,eventTypes:input.eventTypes,createdAt:timestamp};
}

export async function listAgentWebhooks(db:D1Database,ownerSub:string){
  const rows=await db.prepare("SELECT id,organization_id,project_id,label,endpoint,event_types_json,enabled,created_at,updated_at FROM agent_api_webhooks WHERE owner_sub=? ORDER BY created_at DESC").bind(ownerSub).all<{id:string;organization_id:string|null;project_id:string|null;label:string;endpoint:string;event_types_json:string;enabled:number;created_at:string;updated_at:string}>();
  return rows.results.map((row)=>({id:row.id,organizationId:row.organization_id,projectId:row.project_id,label:row.label,endpoint:row.endpoint,eventTypes:JSON.parse(row.event_types_json) as string[],enabled:Boolean(row.enabled),createdAt:row.created_at,updatedAt:row.updated_at}));
}

export async function disableAgentWebhook(db:D1Database,ownerSub:string,webhookId:string){const result=await db.prepare("UPDATE agent_api_webhooks SET enabled=0,updated_at=? WHERE id=? AND owner_sub=?").bind(now(),webhookId,ownerSub).run();return Boolean(result.meta.changes);}

export async function deliverAgentWebhookEvent(env:ControlEnv,input:{ownerSub:string;projectId:string;eventType:string;eventId:string;payload:Record<string,unknown>}){
  const hooks=await env.CONTROL_DB.prepare("SELECT * FROM agent_api_webhooks WHERE owner_sub=? AND enabled=1 AND (project_id IS NULL OR project_id=?)").bind(input.ownerSub,input.projectId).all<{id:string;endpoint:string;secret_ciphertext:string;event_types_json:string}>();
  for(const hook of hooks.results){const eventTypes=JSON.parse(hook.event_types_json) as string[];if(!eventTypes.includes("*")&&!eventTypes.includes(input.eventType))continue;const deliveryId=id("awhd");const timestamp=now();await env.CONTROL_DB.prepare("INSERT OR IGNORE INTO agent_api_deliveries (id,webhook_id,event_type,event_id,payload_json,status,attempts,created_at,updated_at) VALUES (?,?,?,?,?,'queued',0,?,?)").bind(deliveryId,hook.id,input.eventType,input.eventId,JSON.stringify({ownerSub:input.ownerSub,projectId:input.projectId,payload:input.payload}),timestamp,timestamp).run();const delivery=await env.CONTROL_DB.prepare("SELECT status,attempts FROM agent_api_deliveries WHERE webhook_id=? AND event_id=?").bind(hook.id,input.eventId).first<{status:string;attempts:number}>();if(!delivery||delivery.status==="delivered"||delivery.attempts>=5)continue;await env.CONTROL_DB.prepare("UPDATE agent_api_deliveries SET status='delivering',attempts=attempts+1,updated_at=? WHERE webhook_id=? AND event_id=?").bind(timestamp,hook.id,input.eventId).run();try{const body=JSON.stringify({id:input.eventId,type:input.eventType,createdAt:timestamp,data:input.payload});const secret=await decryptSecret(env,hook.secret_ciphertext);const signature=await signAgentWebhook(secret,timestamp,body);const response=await fetch(hook.endpoint,{method:"POST",headers:{"content-type":"application/json","user-agent":"Grok-Build-Agent-API","x-grok-event":input.eventType,"x-grok-delivery":input.eventId,"x-grok-timestamp":timestamp,"x-grok-signature":`sha256=${signature}`},body,redirect:"manual"});if(!response.ok)throw new Error(`Webhook returned ${response.status}`);await env.CONTROL_DB.prepare("UPDATE agent_api_deliveries SET status='delivered',response_status=?,error=NULL,next_attempt_at=NULL,delivered_at=?,updated_at=? WHERE webhook_id=? AND event_id=?").bind(response.status,now(),now(),hook.id,input.eventId).run();}catch(error){const delay=Math.min(3600,60*2**delivery.attempts);await env.CONTROL_DB.prepare("UPDATE agent_api_deliveries SET status='failed',error=?,next_attempt_at=?,updated_at=? WHERE webhook_id=? AND event_id=?").bind(error instanceof Error?error.message.slice(0,2000):"Webhook failed",new Date(Date.now()+delay*1000).toISOString(),now(),hook.id,input.eventId).run();}}
}

export async function retryAgentWebhookDeliveries(env:ControlEnv){const rows=await env.CONTROL_DB.prepare(`SELECT d.event_type,d.event_id,MIN(d.payload_json) payload_json FROM agent_api_deliveries d JOIN agent_api_webhooks w ON w.id=d.webhook_id
  WHERE d.status='failed' AND d.attempts<5 AND d.next_attempt_at<=? AND w.enabled=1 GROUP BY d.event_type,d.event_id ORDER BY MIN(d.next_attempt_at) LIMIT 100`).bind(now()).all<{event_type:string;event_id:string;payload_json:string}>();for(const row of rows.results){const stored=JSON.parse(row.payload_json) as {ownerSub:string;projectId:string;payload:Record<string,unknown>};await deliverAgentWebhookEvent(env,{ownerSub:stored.ownerSub,projectId:stored.projectId,eventType:row.event_type,eventId:row.event_id,payload:stored.payload});}return rows.results.length;}
