ALTER TABLE tasks ADD COLUMN additions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN deletions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN changed_files_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE tasks ADD COLUMN patch_key TEXT;
ALTER TABLE tasks ADD COLUMN verification_key TEXT;
ALTER TABLE tasks ADD COLUMN backup_id TEXT;
