// @vitest-environment node
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { spawn } from "node:child_process";
import { chmod, mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = fileURLToPath(new URL(".", import.meta.url));
let fixture;
let dataRoot;
let origin;
let child;
let baseUrl;

function command(bin, args, cwd) {
  return new Promise((resolve, reject) => {
    const process = spawn(bin, args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
    let output = "";
    process.stdout.on("data", (chunk) => output += chunk);
    process.stderr.on("data", (chunk) => output += chunk);
    process.on("error", reject);
    process.on("close", (code) => code === 0 ? resolve(output) : reject(new Error(output)));
  });
}

async function json(path, options) {
  const response = await fetch(`${baseUrl}${path}`, { ...options, headers: { "Content-Type": "application/json" } });
  return { status: response.status, body: await response.json() };
}

async function waitForTask(id) {
  for (let attempt = 0; attempt < 80; attempt += 1) {
    const result = await json(`/api/tasks/${id}`);
    if (["review", "failed"].includes(result.body.status)) return result.body;
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
  throw new Error("Task did not finish");
}

beforeAll(async () => {
  fixture = await mkdtemp(join(tmpdir(), "grok-web-repo-"));
  dataRoot = await mkdtemp(join(tmpdir(), "grok-web-data-"));
  origin = join(dataRoot, "origin.git");
  await writeFile(join(fixture, "README.md"), "fixture\n");
  await command("git", ["init", "-b", "main"], fixture);
  await command("git", ["config", "user.email", "test@example.com"], fixture);
  await command("git", ["config", "user.name", "Test User"], fixture);
  await command("git", ["add", "README.md"], fixture);
  await command("git", ["commit", "-m", "initial"], fixture);
  await command("git", ["init", "--bare", origin], fixture);
  await command("git", ["remote", "add", "origin", origin], fixture);

  const fakeBin = join(dataRoot, "fake-grok.mjs");
  await writeFile(fakeBin, `#!/usr/bin/env node
import { appendFileSync, writeFileSync } from "node:fs";
const args = process.argv.slice(2);
appendFileSync(${JSON.stringify(join(dataRoot, "args.log"))}, JSON.stringify(args) + "\\n");
if (args.includes("--version")) { console.log("grok 0.2.101-test"); process.exit(0); }
if (args[0] === "mcp" || args[0] === "plugin") { console.log("[]"); process.exit(0); }
const cwd = args[args.indexOf("--cwd") + 1];
if (!args.includes("plan")) writeFileSync(cwd + "/generated.txt", "generated by Grok\\n");
console.log(JSON.stringify({ type: "text", data: "Task complete." }));
console.log(JSON.stringify({ type: "end", sessionId: "11111111-1111-4111-8111-111111111111", stopReason: "end_turn", usage: { total_tokens: 42 } }));
`);
  await chmod(fakeBin, 0o755);
  const binDir = join(dataRoot, "bin");
  await mkdir(binDir);
  const fakeGh = join(binDir, "gh");
  await writeFile(fakeGh, `#!/bin/sh
if [ "$1" = "pr" ] && [ "$2" = "create" ]; then echo "https://github.test/example/pull/1"; fi
exit 0
`);
  await chmod(fakeGh, 0o755);
  const port = 46000 + Math.floor(Math.random() * 1000);
  baseUrl = `http://127.0.0.1:${port}`;
  child = spawn("node", [join(webRoot, "server.mjs")], { cwd: webRoot, env: { ...process.env, PATH: `${binDir}:${process.env.PATH}`, NODE_ENV: "production", PORT: String(port), GROK_WEB_REPO: fixture, GROK_WEB_DATA: dataRoot, GROK_BIN: fakeBin, GROK_WEB_PROTOCOL: "headless" }, stdio: ["ignore", "pipe", "pipe"] });
  for (let attempt = 0; attempt < 80; attempt += 1) {
    try { if ((await fetch(`${baseUrl}/api/bootstrap`)).ok) return; } catch {}
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
  throw new Error("Test server did not start");
}, 20_000);

afterAll(() => child?.kill("SIGTERM"));

describe("local agent service", () => {
  it("runs Grok in a worktree and exposes durable review evidence", async () => {
    const created = await json("/api/tasks", { method: "POST", body: JSON.stringify({ prompt: "Create the generated fixture" }) });
    expect(created.status).toBe(201);
    const task = await waitForTask(created.body.id);
    expect(task.status).toBe("review");
    expect(task.sessionId).toBeTruthy();
    expect(task.changedFiles).toEqual([expect.objectContaining({ path: "generated.txt", status: "??" })]);

    const diff = await json(`/api/tasks/${task.id}/diff`);
    expect(diff.body.patch).toContain("generated by Grok");
    const file = await json(`/api/tasks/${task.id}/file?path=generated.txt`);
    expect(file.body.content).toBe("generated by Grok\n");
    const terminal = await json(`/api/tasks/${task.id}/terminal`, { method: "POST", body: JSON.stringify({ command: "git status --short" }) });
    expect(terminal.body.stdout).toContain("generated.txt");
    const secret = await json(`/api/tasks/${task.id}/terminal`, { method: "POST", body: JSON.stringify({ command: "printf 'sk-123456789012345678901234567890'" }) });
    expect(secret.body.stdout).toBe("[REDACTED]");
    const preview = await json(`/api/tasks/${task.id}/preview`, { method: "POST", body: JSON.stringify({ command: "node -e \"console.log('ready'); setInterval(() => {}, 1000)\"" }) });
    expect(preview.body.url).toMatch(/^http:\/\/127\.0\.0\.1:/);
    const stopped = await json(`/api/tasks/${task.id}/preview`, { method: "DELETE" });
    expect(stopped.body.status).toBe("stopped");
    const traversal = await json(`/api/tasks/${task.id}/file?path=../../README.md`);
    expect(traversal.status).toBe(500);
    expect((await json(`/api/tasks/${task.id}`, { method: "DELETE" })).body.archived).toBe(true);
    expect((await json(`/api/tasks/${task.id}/restore`, { method: "POST", body: "{}" })).body.id).toBe(task.id);
    const published = await json(`/api/tasks/${task.id}/pull-request`, { method: "POST", body: JSON.stringify({ title: "Fixture PR" }) });
    expect(published.body.url).toBe("https://github.test/example/pull/1");
    expect(await command("git", ["--git-dir", origin, "show-ref", "--verify", `refs/heads/${task.branch}`], fixture)).toContain(task.branch);
  });

  it("enforces review-only mode at the Grok process boundary", async () => {
    const created = await json("/api/tasks", { method: "POST", body: JSON.stringify({ prompt: "Inspect only", permissionMode: "review-only" }) });
    const task = await waitForTask(created.body.id);
    expect(task.changedFiles).toEqual([]);
    const invocations = await readFile(join(dataRoot, "args.log"), "utf8");
    expect(invocations).toContain('"--permission-mode","plan"');
    expect(invocations).toContain('"Bash(*)"');
  });

  it("persists schedules and launches automation runs in isolated tasks", async () => {
    const created = await json("/api/automations", { method: "POST", body: JSON.stringify({ name: "Hourly audit", prompt: "Inspect the fixture", schedule: "hourly" }) });
    expect(created.status).toBe(201);
    expect(created.body.nextRunAt).toBeTruthy();
    const run = await json(`/api/automations/${created.body.id}/run`, { method: "POST", body: "{}" });
    expect(run.status).toBe(202);
    expect(run.body.source).toBe("automation");
    expect((await waitForTask(run.body.id)).status).toBe("review");
  });

  it("manages MCP servers and trusted plugins through canonical Grok commands", async () => {
    const mcp = await json("/api/connectors/mcp", { method: "POST", body: JSON.stringify({ name: "linear", target: "npx", args: ["@example/mcp"], transport: "stdio", scope: "project" }) });
    expect(mcp.status).toBe(201);
    const plugin = await json("/api/connectors/plugins", { method: "POST", body: JSON.stringify({ source: "github:example/plugin", confirmed: true }) });
    expect(plugin.status).toBe(201);
    const denied = await json("/api/connectors/plugins", { method: "POST", body: JSON.stringify({ source: "github:example/untrusted", confirmed: false }) });
    expect(denied.status).toBe(500);
    const invocations = await readFile(join(dataRoot, "args.log"), "utf8");
    expect(invocations).toContain('["mcp","add","--transport","stdio","--scope","project","linear","--","npx","@example/mcp"]');
    expect(invocations).toContain('["plugin","install","--trust","github:example/plugin"]');
    expect(invocations).not.toContain("github:example/untrusted");
  });
});
